release: 0.13.1
MonacoProtocol/protocol pull request #192
Opened 2024-03-08 16:14 UTC by pawel-betdex

Pre 0.14.0 release to help us clean up some accounts before introducing more account changes in 0.14.0. 

Adding `initialize_market_queues` endpoint that allows us to create missing market matching queues to close market accounts created before 0.13.0 release. Markets without `MarketMatchingQueue` fail to close since `close_market` endpoint requires a valid PK for it.

2024-03-08 16:30 UTC, eoin-betdex requested changes
Needs version changed in cargo.toml and lock.

2024-03-11 12:57 UTC, obi-ewan approved these changes

2024-03-11 13:15 UTC, eoin-betdex submitted a review, later dismissed

2024-04-29 10:04 UTC, pawel-betdex commented
the code serve its purpose and we do not intend to merge it to the main so closing

2024-04-29 10:04 UTC, closed without merging